kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://172.17.0.1:5000"]
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 81
    protocol: TCP
  - containerPort: 443
    hostPort: 444
    protocol: TCP
  - containerPort: 53
    hostPort: 5054
    protocol: UDP
