theme: jekyll-theme-cayman
markdown: GFM
include:
  - CONTRIBUTING.md
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
google_analytics: G-HMZ7QVHJH0
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
relative_links:
  enabled: true
  collections: true
