theme: jekyll-theme-cayman
markdown: GFM
include:
  - CONTRIBUTING.md
exclude:
  - Gemfile
  - Gemfile.lock
google_analytics: G-HMZ7QVHJH0
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
