{{ if .Values.route53.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-route53
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-route53
  template:
    metadata:
      labels:
        app: external-dns-route53
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: {{ .Values.externaldns.image }}
        args:
        - --source=crd
        - --domain-filter={{ .Values.route53.domain }} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --annotation-filter=k8gb.absa.oss/dnstype=route53 # filter out only relevant DNSEntrypoints
        - --provider=aws
        - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
        - --registry=txt
        - --txt-owner-id= {{ .Values.route53.hostedZoneID }}
        - --log-level=debug # debug only
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files
{{ end }}
