apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: {{ .Release.Namespace }}
{{ if .Values.route53.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.route53.irsaRole }}
{{ end }}
