# Standalone ConfigMap to expose coredns in Rancher
# without any other ingress contoller reconfiguration
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: kgb
data:
  53: "kgb/kgb-coredns:53"
