{{ if .Values.infoblox.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-infoblox
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-infoblox
  template:
    metadata:
      labels:
        app: external-dns-infoblox
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: {{ .Values.externaldns.image }}
        args:
        - --source=crd
        - --domain-filter={{ .Values.infoblox.dnsZone }}       # (optional) limit to only example.com domains.
        - --provider=infoblox
        - --annotation-filter=ohmyglb.absa.oss/dnstype=edgedns # filter out only relevant DNSEntrypoints
        - --infoblox-grid-host={{ .Values.infoblox.gridHost }} # (required) IP of the Infoblox Grid host.
        - --infoblox-wapi-port=443          # (optional) Infoblox WAPI port. The default is "443".
        - --infoblox-wapi-version=2.3.1     # (optional) Infoblox WAPI version. The default is "2.3.1"
        {{ if .Values.infoblox.sslVerify }}
        - --infoblox-ssl-verify             # (optional) Use --no-infoblox-ssl-verify to skip server certificate verification.
        {{ else }}
        - --no-infoblox-ssl-verify
        {{ end }}
        - --log-level=debug # debug only
        - --txt-owner-id=ohmyglb-{{ .Values.ohmyglb.clusterGeoTag }} # to differnetiate between multiple instances
        env:
        - name: EXTERNAL_DNS_INFOBLOX_HTTP_POOL_CONNECTIONS
          value: "10" # (optional) Infoblox WAPI request connection pool size. The default is "10".
        - name: EXTERNAL_DNS_INFOBLOX_HTTP_REQUEST_TIMEOUT
          value: "60" # (optional) Infoblox WAPI request timeout in seconds. The default is "60".
        - name: EXTERNAL_DNS_INFOBLOX_WAPI_USERNAME
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: EXTERNAL_DNS_INFOBLOX_WAPI_USERNAME
        - name: EXTERNAL_DNS_INFOBLOX_WAPI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: external-dns
              key: EXTERNAL_DNS_INFOBLOX_WAPI_PASSWORD
{{ end }}
