apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohmyglb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ohmyglb
  template:
    metadata:
      labels:
        name: ohmyglb
    spec:
      serviceAccountName: ohmyglb
      containers:
        - name: ohmyglb
          # Replace this with the built image name
          image: ytsarev/ohmyglb:v0.0.2
          command:
          - ohmyglb
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ohmyglb"
