global:
  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"

k8gb:
  imageRepo: absaoss/k8gb # image tag is defined in Chart.AppVersion, see Chart.yaml
  ingressNamespace: "k8gb"
  dnsZone: &dnsZone "cloud.example.com" # dnsZone controlled by gslb
  edgeDNSZone: &edgeDNSZone "example.com" # main zone which would contain gslb zone to delegate
  edgeDNSServer: &edgeDNSServer "1.1.1.1" # to handle splitbrain situation with TXT timestamp
  clusterGeoTag: "eu" # used for places where we need to distinguish between differnet Gslb instances
  extGslbClustersGeoTags: "us" # comma-separated list of external gslb geo tags to pair with
  hostAlias: # use https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/ inside operator pod. Useful for advanced testing scenarios and to break dependency on EdgeDNS for cross k8gb collaboration
    enabled: false
    ip: "172.17.0.1"
    hostnames:
     - "test-gslb-ns-us.example.com"
     - "test-gslb-failover-ns-us.example.com"
  reconcileRequeueSeconds: 30

externaldns:
  image: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.7.2
  interval: "20s"

etcd-operator:
  customResources:
    createEtcdClusterCRD: true
  etcdOperator:
    image:
      repository: quay.io/coreos/etcd-operator
      tag: v0.9.4
  backupOperator:
    image:
      repository: quay.io/coreos/etcd-operator
      tag: v0.9.4
  restoreOperator:
    image:
      repository: quay.io/coreos/etcd-operator
      tag: v0.9.4
  etcdCluster:
    image:
      repository: quay.io/coreos/etcd
    version: 3.2.25
    pod:
      busyboxImage: busybox:1.28.0-glibc

coredns:
  isClusterService: false
  image:
    repository: coredns/coredns
    tag: "1.6.6"
  servers:
  - zones:
    - zone: .
    port: 53
    plugins:
    - name: cache
      parameters: 30
    - name: errors
    # Serves a /health endpoint on :8080, required for livenessProbe
    - name: health
    # Serves a /ready endpoint on :8181, required for readinessProbe
    - name: ready
    # Required to query kubernetes API for data
    - name: kubernetes
      parameters: cluster.local
    - name: loadbalance
      parameters: round_robin
    # Serves a /metrics endpoint on :9153, required for serviceMonitor
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: forward
      parameters: . /etc/resolv.conf
    - name: etcd
      parameters: *dnsZone
      configBlock: |-
        stubzones
        path /skydns
        endpoint http://etcd-cluster-client:2379

infoblox:
  enabled: false
  gridHost: 10.0.0.1
  wapiVersion: 2.3.1
  wapiPort: 443
  sslVerify: true
