apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgb
  namespace: kgb
  labels:
{{ include "chart.labels" . | indent 4  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kgb
  template:
    metadata:
      labels:
        name: kgb
    spec:
      {{ if .Values.kgb.hostAlias.enabled }}
      hostAliases:
        - ip: "{{ .Values.kgb.hostAlias.ip }}"
          hostnames:
          - "{{ .Values.kgb.hostAlias.hostname }}"
      {{ end }}
      serviceAccountName: kgb
      containers:
        - name: kgb
          image: {{ .Values.kgb.imageRepo }}:v{{ .Chart.AppVersion }}
          command:
          - kgb
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kgb"
            - name: KGB_VERSION
              value: {{ quote .Chart.AppVersion }}
            - name: CLUSTER_GEO_TAG
              value: {{ quote .Values.kgb.clusterGeoTag }}
            - name: EXT_GSLB_CLUSTERS_GEO_TAGS
              value: {{ quote .Values.kgb.extGslbClustersGeoTags }}
            - name: EDGE_DNS_ZONE
              value: {{ .Values.kgb.edgeDNSZone }}
            - name: EDGE_DNS_SERVER
              value: {{ .Values.kgb.edgeDNSServer }}
            - name: DNS_ZONE
              value: {{ .Values.kgb.dnsZone }}
            - name: RECONCILE_REQUEUE_SECONDS
              value: {{ quote .Values.kgb.reconcileRequeueSeconds}}
            {{ if .Values.infoblox.enabled }}
            - name: INFOBLOX_GRID_HOST
              valueFrom:
                configMapKeyRef:
                  name: infoblox
                  key: INFOBLOX_GRID_HOST
            - name: INFOBLOX_WAPI_VERSION
              valueFrom:
                configMapKeyRef:
                  name: infoblox
                  key: INFOBLOX_WAPI_VERSION
            - name: INFOBLOX_WAPI_PORT
              valueFrom:
                configMapKeyRef:
                  name: infoblox
                  key: INFOBLOX_WAPI_PORT
            - name: EXTERNAL_DNS_INFOBLOX_WAPI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: external-dns
                  key: EXTERNAL_DNS_INFOBLOX_WAPI_USERNAME
            - name: EXTERNAL_DNS_INFOBLOX_WAPI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: external-dns
                  key: EXTERNAL_DNS_INFOBLOX_WAPI_PASSWORD
            {{ end }}

