name: Helm Publish

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Operator image build and push
        env:
          OPERATOR_SDK_VERSION: v0.16.0
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          wget https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu -O ./operator-sdk
          chmod +x ./operator-sdk
          export PATH=.:$PATH
          docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
          make build
          make push
      - uses: dave-mcconnell/helm-gh-pages-microservices@master
        with:
          access-token: ${{ secrets.CR_TOKEN }}
          source-charts-folder: 'chart'
          destination-repo: absaoss/k8gb
          destination-branch: gh-pages
      - name: Create single node k8s Kind Cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          cluster_name: test-gslb1
          config: deploy/kind/cluster-terratest.yaml
      - name: Smoke test helm installation
        run: |
           helm repo add k8gb https://absaoss.github.io/k8gb/
           helm repo update
           helm -n k8gb upgrade -i k8gb k8gb/k8gb --wait --create-namespace --version=$(make version)

