name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag
        id: get_tag
        run: |
          previous_tag=$(git tag --sort=v:refname | tail -2 | head -1)
          echo "::set-output name=previous_tag::${previous_tag}"
      - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project: k8gb
          sinceTag: ${{ steps.get_tag.outputs.previous_tag }}
          output: changes
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Hack around until https://github.com/goreleaser/goreleaser/pull/2119 is fixed
      - name: Operator image build and push
        run: |
          export PATH=~/go/bin:$PATH
          make docker-build-multi
          make docker-push-multi
          make docker-manifest
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes=changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
