name: Terratest

on: push

jobs:
  terratest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create 1st k8s Kind Cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          cluster_name: test-gslb1
          config: deploy/kind/cluster-terratest.yaml
      - name: Create 2nd k8s Kind Cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          cluster_name: test-gslb2
          config: deploy/kind/cluster2-terratest.yaml
          wait: 180s
      - name: Ohmyglb deployment
        env:
          NODE_ROLE: control-plane
          TEST_CURRENT_COMMIT: yes
        run: |
          OPERATOR_SDK_VERSION=v0.16.0
          wget https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu -O ./operator-sdk
          chmod +x ./operator-sdk
          export PATH=.:$PATH
          export VERSION=$(make version)
          ./deploy/full.sh
          kubectl get pods -A
          make use-second-context
          kubectl get pods -A
      - name: Terratest
        run: make terratest
