name: Terratest

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.drawio'
      - '.spelling'

jobs:
  terratest-lb:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Create 1st k3s Cluster
        uses: AbsaOSS/k3d-action@v1.3.1
        with:
          cluster-name: "test-gslb1"
          args: -c k3d/lb/test-gslb1.yaml

      - name: Create 2nd k3s Cluster
        uses: AbsaOSS/k3d-action@v1.3.1
        with:
          cluster-name: "test-gslb2"
          args: -c k3d/lb/test-gslb2.yaml

      - name: K8GB deployment
        run: make deploy-candidate

      - name: Terratest
        run: make terratest

  terratest-ingress:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Create 1st k3s Cluster
        uses: AbsaOSS/k3d-action@v1.3.1
        with:
          cluster-name: "test-gslb1"
          args: -c k3d/ingress/test-gslb1.yaml

      - name: Create 2nd k3s Cluster
        uses: AbsaOSS/k3d-action@v1.3.1
        with:
          cluster-name: "test-gslb2"
          args: -c k3d/ingress/test-gslb2.yaml

      - name: K8GB deployment
        env:
          COREDNS_TYPE: ingress
        run: |
          make deploy-candidate

      - name: Terratest
        run: make terratest
