global:
  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"

ohmyglb:
  image: ytsarev/ohmyglb:v0.3.2
  ingressNamespace: "ohmyglb"
  dnsZone: &dnsZone "cloud.example.com"
  edgeDNSZone: &edgeDNSZone "example.com"
  extGslbClusters: "" # comma-separated list of FQDNs pointing to external Gslb enabled clusters to work with
  clusterGeoTag: "eu" # used for places where we need to distinguish between differnet Gslb instances

externaldns:
  image: ytsarev/external-dns:v0.5.18-27-g432d0696-dirty

etcd-operator:
  customResources:
    createEtcdClusterCRD: true
  etcdOperator:
    image:
      repository: quay.io/coreos/etcd-operator
      tag: v0.9.4
  backupOperator:
    image:
      repository: quay.io/coreos/etcd-operator
      tag: v0.9.4
  restoreOperator:
    image:
      repository: quay.io/coreos/etcd-operator
      tag: v0.9.4
  etcdCluster:
    image:
      repository: quay.io/coreos/etcd
      tag: v3.2.25
    pod:
      busyboxImage: busybox:1.28.0-glibc

coredns:
  isClusterService: false
  image:
    repository: coredns/coredns
    tag: "1.6.6"
  servers:
  - zones:
    - zone: .
    port: 53
    plugins:
    - name: cache
      parameters: 30
    - name: errors
    # Serves a /health endpoint on :8080, required for livenessProbe
    - name: health
    # Serves a /ready endpoint on :8181, required for readinessProbe
    - name: ready
    # Required to query kubernetes API for data
    - name: kubernetes
      parameters: cluster.local
    - name: loadbalance
      parameters: round_robin
    # Serves a /metrics endpoint on :9153, required for serviceMonitor
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: forward
      parameters: . /etc/resolv.conf
    - name: etcd
      parameters: *dnsZone
      configBlock: |-
        stubzones
        path /skydns
        endpoint http://etcd-cluster-client:2379

infoblox:
  enabled: false
  dnsZone: *edgeDNSZone # main zone which would contain gslb zone to delegate
  gridHost: 10.0.0.1
